urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from website.views.site import HomepePageView

admin.site.site_header = 'Rigips Trophy'


urlpatterns = [
    url('^$', HomepePageView.as_view(), name='website.index'),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/models/configuration.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from uuid import uuid4
from django.db import models
from solo.models import SingletonModel

_UNSAVED_FILEFIELD = 'unsaved_filefield'


def upload_path_handler(instance, filename):
    return "regulamin/{hex}/{filename}".format(hex=uuid4().hex, filename=filename)


class Configuration(SingletonModel):
    rule_file = models.FileField("Plik z regulaminem", null=True, blank=True, upload_to=upload_path_handler)
    condition_file = models.FileField("Plik zformularzem zgody na wykorzystanie zdjęć", null=True, blank=True, upload_to=upload_path_handler)

    def __unicode__(self):
        return u"Konfiguracja"

    class Meta:
        verbose_name = "Konfiguracja"

apps/website/models/registration.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField


_UNSAVED_FILEFIELD = 'unsaved_filefield'


def upload_path_handler(instance, filename):
    return "registration/{id}/images/{filename}".format(id=instance.registration_id, filename=filename)


def upload_path_handler_scan(instance, filename):
    return "registration/{id}/scans/{filename}".format(id=instance.pk, filename=filename)


class Registration(models.Model):

    CATEGORY_CHOICES = (
        ("1", "Płyty gipsowo-kartonowe"),
        ("2", "Rozwiązania innowacyjne i nienaruszające równowagi środowiskowej"),
        ("3", "Budynki mieszkalne"),
        ("4", "Rozwiązania sektorowe"),
        ("5", "Sufity"),
    )

    created_at = models.DateTimeField("Data utworzenia", auto_now_add=True)
    company_name = models.CharField("Nazwa firmy", max_length=255)
    category = MultiSelectField("Kategoria konkursowa", max_length=255, choices=CATEGORY_CHOICES)
    name = models.CharField("Imię i nazwisko", max_length=255)
    company_address = models.TextField("Adres firmy", default="")
    phone = models.CharField("Telefon", max_length=255)
    fax = models.CharField("Faks", max_length=255, blank=True, null=True)
    email = models.EmailField("E-mail", max_length=255)
    allow_scan = models.FileField("Skan zgody", blank=True, null=True, upload_to=upload_path_handler_scan)
    description_1 = models.TextField("Krótki opis budowy", default="")
    description_2 = models.TextField("Zastosowane rozwiązania", default="")
    description_3 = models.TextField("Zastosowane systemy Rigips",
                                     default="",
                                     help_text="Rozwiązania, które wyróżniają projekt np nietypowe pomieszczenie, "
                                               "krótki czas realizacji przy skomplikowanych rozwiązaniach, "
                                               "dźwięko-chłonność, zabezpieczenia, nietypowe rozwiązania ppoż.")

    class Meta:
        app_label = 'website'
        verbose_name = "Zgłoszenie"
        verbose_name_plural = "Zgłoszenia"

    def __unicode__(self):
        return self.name


class RegistrationFile(models.Model):

    registration = models.ForeignKey("website.Registration")
    created_at = models.DateTimeField("Data utworzenia", auto_now_add=True)
    file = models.FileField("Załacznik", upload_to=upload_path_handler)

    app_label = 'website'
    verbose_name = "Załącznik"
    verbose_name_plural = "Załączniki"


@receiver(pre_save, sender=Registration)
def skip_saving_scan(sender, instance, **kwargs):
    if not instance.pk and not hasattr(instance, _UNSAVED_FILEFIELD):
        setattr(instance, _UNSAVED_FILEFIELD, instance.allow_scan)
        instance.allow_scan = None


@receiver(post_save, sender=Registration)
def save_scan(sender, instance, created, **kwargs):
    if created and hasattr(instance, _UNSAVED_FILEFIELD):
        instance.allow_scan = getattr(instance, _UNSAVED_FILEFIELD)
        instance.save()


@receiver(pre_save, sender=RegistrationFile)
def skip_saving_file(sender, instance, **kwargs):
    if not instance.pk and not hasattr(instance, _UNSAVED_FILEFIELD):
        setattr(instance, _UNSAVED_FILEFIELD, instance.file)
        instance.file = None


@receiver(post_save, sender=RegistrationFile)
def save_file(sender, instance, created, **kwargs):
    if created and hasattr(instance, _UNSAVED_FILEFIELD):
        instance.file = getattr(instance, _UNSAVED_FILEFIELD)
        instance.save()

apps/website/forms/registration_form.py
# coding=utf-8
from django import forms
from website.models import Registration


class RegistrationForm(forms.ModelForm):
    files = forms.FileField(label='Pliki', required=True)
    checkbox_1 = forms.BooleanField(
        label="", required=True)
    checkbox_2 = forms.BooleanField(
        label="", required=True)

    class Meta:
        model = Registration
        exclude = ['pk']

apps/website/views/site.py
# -*- encoding: utf-8 -*-
from django.shortcuts import redirect
from django.views.generic import FormView
from website.forms.registration_form import RegistrationForm
from website.models.configuration import Configuration
from website.models.registration import RegistrationFile
from django.contrib import messages
import magic


class HomepePageView(FormView):
    template_name = 'website/site/homepage.html'
    form_class = RegistrationForm
    ALLOW_MIME_TYPES = ['image/png', 'image/jpeg']
    ALLOW_MIME_TYPES_SCAN = ALLOW_MIME_TYPES + ['application/pdf', 'application/x-pdf']

    def get_context_data(self, **kwargs):
        context = super(HomepePageView, self).get_context_data(**kwargs)
        context["configuration"] = Configuration.get_solo()
        return context

    def form_invalid(self, form):
        messages.error(self.request, u'Formularz zawiera błędy', extra_tags='error')
        return super(HomepePageView, self).form_invalid(form)

    def get_success_url(self):
        return "/"

    def form_valid(self, form):

        obj = form.save(commit=False)

        all_files_ok = True
        files_list = self.request.FILES.getlist('files')

        if len(files_list) > 5:
            form.add_error('files', u'Dopuszczalna ilość plików to 5')
            messages.error(self.request, u'Formularz zawiera błędy', extra_tags='error')
            return self.form_invalid(form)

        scan_file = self.request.FILES.get('allow_scan')
        if scan_file:
            if magic.from_buffer(scan_file.read(1024), mime=True) not in self.ALLOW_MIME_TYPES_SCAN or scan_file.size > 5000000:
                all_files_ok = False
                form.add_error('allow_scan', u'Niewłaściwy format pliku lub zbyt duży plik')

        for f in files_list:
            if magic.from_buffer(f.read(1024), mime=True) not in self.ALLOW_MIME_TYPES:
                all_files_ok = False

            if f.size > 5000000:
                all_files_ok = False

        if all_files_ok:
            obj.save()

            for f in self.request.FILES.getlist('files'):
                RegistrationFile(registration=obj, file=f).save()

            messages.success(self.request, u'Pomyślnie wysłano zgłoszenie', extra_tags='success')
        else:
            form.add_error('files', u'Błędny format lub zbyt duzy plik')
            messages.error(self.request, u'Formularz zawiera błędy', extra_tags='error')
            return self.form_invalid(form)

        return super(HomepePageView, self).form_valid(form)

apps/website/templates/website/admin/change_form_registration.html
{% extends "admin/change_form.html" %}

{% block content_title %}
{% if title %}
<div class="row">
    <div class="col-lg-12"><h2 class="text-primary">Podgląd złoszenia</h2></div>
</div>
{% endif %}
{% endblock %}

{% block site_links_area %}{% endblock %}


{% block field_sets %}
{{ block.super}}
{% with object=adminform.form.instance %}
<style>
    td.original p{
        display: none;
    }
    .inline-group .tabular tr.has_original td{
        padding-top: 0;
    }
    .historylink{
        display: none !important;
    }
    .export{
        border: 1px solid #ccc;
        padding: 2px 10px;
        margin: 0;
        vertical-align: middle;
        background: #fff;
        box-shadow: 0 -15px 20px -10px rgba(0, 0, 0, 0.15) inset;
        cursor: pointer;
        color: #333;
    }
</style>

<script>
    (function($){
        $(function(){
            $(".submit-row").html('<a href="{% url 'admin:website_registration_changelist' %}{% if changelist_filters %}?{{ changelist_filters|safe }}{% endif %}" class="button default" style="padding: 8px 15px;">Powrót do listy</a>');
            $(".field-file a").attr("target", "_blank");
        });
    })(django.jQuery);
</script>

{% endwith %}
{% endblock %}

apps/website/templates/website/admin/change_list_registration.html
{% extends "admin/change_list.html" %}


{% block content %}
{{ block.super}}

<style>
    .export{
        border: none !important;
        font-weight: 400 !important;
        background: #417690 !important;
        border-radius: 4px !important;
        color: #fff !important;
        width: 50px !important;
        text-align: center !important;
        padding: 3px !important;
    }
</style>

<script>
    (function($){

        $(function(){

            $("#changelist-search > div").append('<input class="button default export" value="Export">');

            $("input.export").on("click", function () {
                if (!$("#action-toggle").is(":checked")) {
                    $("#action-toggle").click();
                }
                $(".actions select[name=action]").val('export_items');
                $("div.actions input.select-across").val(1);
                $("span.question").hide();
                $("span.clear").show();


                var options = {
                    actionContainer: "div.actions",
                    counterContainer: "span.action-counter",
                    allContainer: "div.actions span.all",
                    acrossInput: "div.actions input.select-across",
                    acrossQuestions: "div.actions span.question",
                    acrossClears: "div.actions span.clear",
                    allToggle: "#action-toggle",
                    selectedClass: "selected"
                };

                $(options.acrossInput).val(1);
                $(options.acrossClears).show();
                $(options.acrossQuestions).hide();
                $(options.actionContainer).toggleClass(options.selectedClass);
                $(options.allContainer).show();
                $(options.counterContainer).hide();
                $(".actions button[type=submit]").click();
                //$("span.clear a").click();
                if ($("#action-toggle").is(":checked")) {
                    $("#action-toggle").click();
                }
            });

        });
    })(django.jQuery);
</script>


{% endblock %}

apps/website/templates/website/site/_conditions.html
{% load static %}{% load compress %}
<div class="skos_5">
    <div class="skos-5-content-wrapper">
        <div class="col-sm-12 warunki-margin">
            <h2 class=" text-center " style="margin-top: 0px;">
                WARUNKI UDZIAŁU
            </h2>
        </div>
        <div class="container condition-wrapper">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 hidden-xs hidden-sm"></div>
                <div class=" col-xs-12 col-sm-12 col-md-6 rectangle triangle-right triangle-01"><p class="right-triangle-padding">Zastosowanie w zgłaszanym obiekcie systemów RIGIPS <br>(w zakresie suchej zabudowy)</p></div>
            </div>
            <div class="row">
                <div class=" col-xs-12 col-sm-12 col-md-6 rectangle triangle-left triangle-02"><p class="left-triangle-padding">Przesłanie przez firmę krótkiego opisu procesu zabudowy, ze szczególnym uwzględnieniem nietypowych, trudnych rozwiązań oraz specyfikacją zastosowanych systemów</p></div>
                <div class="col-xs-12 col-sm-12 col-md-6 hidden-xs hidden-sm"></div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 hidden-xs hidden-sm"></div>
                <div class=" col-xs-12 col-sm-12 col-md-6 rectangle triangle-right triangle-03"><p class="right-triangle-padding">Dostarczenie dokumentacji fotograficznej obiektu <br>(w trakcie zabudowy oraz ukończonej realizacji)</p></div>
            </div>
            <div class="row">
                <div class=" col-xs-12 col-sm-12 col-md-6 rectangle triangle-left triangle-04"><p class="left-triangle-padding">Uzyskanie zgody autora projektu i inwestora na publikację zdjęć obiektu oraz wykorzystanie ich w materiałach reklamowych Saint-Gobain/RIGIPS.
                    <a href="{% if configuration.condition_file %}{{ configuration.condition_file.url }}{% endif %}" target="_blank">Pobierz formularze zgód na wykorzystanie zdjęć.</a></p></div>
                <div class="col-xs-12 col-sm-12 col-md-6 hidden-xs hidden-sm"></div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 hidden-xs hidden-sm"></div>
                <div class=" col-xs-12 col-sm-12 col-md-6 rectangle triangle-right right-3 triangle-05"><p class="right-triangle-padding">Przesłanie zgłoszenia do 20.07.2017 r.</p></div>
            </div>
            <div class="row">
                <div class="col-sm-12 reward-wrapper">
                    <div class="row">
                    <div class="col-sm-5 col-sm-offset-1">
                    <div class="">
                        <h2 class="reward-title">Zwycięzca</h2>
                        <p class="reward-text">
                           Zwycięskie obiekty będą reprezentowały Polskę<br/>w międzynarodowej edycji konkursu, a przedstawicieli firm wykonawczych zaprosimy w 2018 roku na uroczyste ogłoszenie wyników, które odbędzie się w marcu w Lizbonie.
                        </p>
                    </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

apps/website/templates/website/site/_footer.html
{% load static %}{% load widget_tweaks %}

<div class="footer-wrapper">
    <div class="container">
        <div class="row">
        <div class="col-sm-6">
            <a href="http://www.rigips.pl/"  target="_blank"><img class="img-responsive rigips-logo" src="{% static 'website/images/rigips_white.png' %}" alt=""></a>
        </div>
        <div class="col-sm-6 text-right">
            <div class="contact-wrapper">
                Adrianna Przedpełska<br/>
                e-mail: <a href="mailto:">adrianna.przedpelska-kot@saint-gobain.com</a><br/>
                tel.: <a href="tel:+48662227212">+48 662 227 212</a>
            </div>
        </div>
        </div>
    </div>
</div>

apps/website/templates/website/site/_form.html
{% load static %}{% load widget_tweaks %}
<div class="form-wrapper">
<div class="container blue-wrapper">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="form-title text-center ">
                ZGŁOŚ PROJEKT
            </h2>
            <div class="col-xs-4"></div>
             <div class="col-xs-4 green-border"></div>
             <div class="col-xs-4"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">

            {% if messages %}
                {% for message in messages %}
                <div class="alert type-{{ message.tags }}" role="alert">
                {{ message }}
                </div>
                {% endfor %}

                <script>
                    $(function(){
                        setTimeout(function(){
                            $('html, body').animate({
                                scrollTop: $('.alert:first').offset().top - 100
                            }, 1000);
                        }, 300);
                    });
                </script>

            {% endif %}
            <br/>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-sm-2 col-md-2 hidden-xs hidden-sm"></div>
        <div class="col-12 col-sm-12 col-md-8 form-wrapper-padding">

            <form action="." method="post" enctype="multipart/form-data">
                {{ form.non_field_errors }}
                <div class="form-group">
                    <label for="{{ form.company_name.auto_id }}">{{ form.company_name.label }} *</label>
                    {% render_field form.company_name class="form-control" %}
                    {{ form.company_name.errors }}
                </div>

                <div class="form-group col-md-6 col-xs-12 form-group-left">
                    <label for="{{ form.name.auto_id }}">{{ form.name.label }} *</label>
                    {% render_field form.name class="form-control" %}
                    {{ form.name.errors }}
                </div>
                  <div class="form-group col-md-6 col-xs-12 form-group-right">
                    <label for="{{ form.email.auto_id }}">{{ form.email.label }} *</label>
                    {% render_field form.email class="form-control" %}
                    {{ form.email.errors }}
                </div>
                <div class="form-group col-md-6 col-xs-12 form-group-left">
                    <label for="{{ form.phone.auto_id }}">{{ form.phone.label }} *</label>
                    {% render_field form.phone class="form-control" %}
                    {{ form.phone.errors }}
                    {{ form.phone.errors }}
                </div>
                <div class="form-group col-md-6 col-xs-12 form-group-right">
                    <label for="{{ form.fax.auto_id }}">{{ form.fax.label }}</label>
                    {% render_field form.fax class="form-control" %}
                    {{ form.fax.errors }}
                </div>

                <div class="form-group">
                    <label for="{{ form.company_address.auto_id }}">{{ form.company_address.label }} *</label>
                    {% render_field form.company_address class="form-control auto-expand" %}
                    {{ form.company_address.errors }}
                </div>

                <div class="form-group">
                    <label for="{{ form.description_1.auto_id }}">{{ form.description_1.label }} *</label>
                    {% render_field form.description_1 class="form-control auto-expand"  %}
                    {{ form.description_1.errors }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description_2.auto_id }}">{{ form.description_2.label }} *</label>
                    {% render_field form.description_2 class="form-control auto-expand" %}
                    {{ form.description_2.errors }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description_3.auto_id }}">{{ form.description_3.label }} *</label>
                    {% render_field form.description_3 class="form-control auto-expand" %}
                    {{ form.description_3.errors }}
                </div>

                <div class="form-group">
                    <label for="id_files">Zdjęcia *</label>

                    <div class="drop-area">
                        {% render_field form.files multiple="multiple" accept=".jpg,.jpeg,.png" %}

                        <div class="drop-text"><i class="fa fa-upload inline" aria-hidden="true"></i><h3 class="inline icon">Kliknij lub upuść pliki ze zdjęciami tutaj</h3></div>
                    </div>
                    <div class="files-error">
                        {{ form.files.errors }}
                    </div>

                    <div class="small text-muted text-center">Maksymalny rozmiar pojedynczego pliku to 5 MB (maks. 5 plików). Dozwolone
                        formaty plików to JPG oraz PNG.
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_allow_scan">Skan zgody na wykorzystanie zdjęć</label>

                    <div class="drop-area">
                        {% render_field form.allow_scan accept=".jpg,.jpeg,.png,.pdf" %}

                        <div class="drop-text"><i class="fa fa-upload inline" aria-hidden="true"></i><h3 class="inline icon">Kliknij lub upuść pliki ze zdjęciami tutaj</h3></div>
                    </div>
                    <div class="files-error">
                        {{ form.allow_scan.errors }}
                    </div>

                    <div class="small text-muted text-center">Maksymalny rozmiar pliku to 5 MB. Dozwolone
                        formaty plików to JPG oraz PNG.
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form.category.auto_id }}">{{ form.category.label }} *</label>

                    {% for value, text in form.category.field.choices %}
                      <div class="checkbox">
                          <input class="sc-checkbox" id="id_category_{{ forloop.counter0 }}" name="{{ form.category.name }}" type="checkbox" value="{{ value }}"{% if value in checked_providers %} checked="checked"{% endif %}>
                        <label class="material-checkbox" for="id_category_{{ forloop.counter0 }}">
                            <span class="checkbox-font">{{ text }}</span>
                        </label>
                      </div>
                    {% endfor %}

                    {{ form.category.errors }}
                    <div class="small text-muted text-right">* Pola wymagane</div>
                </div>

                <div class="checkbox small checkbox-text">
                    {% render_field form.checkbox_1 class="sc-checkbox" %}
                    <label for="{{ form.checkbox_1.auto_id }}" class="material-checkbox">

                         <span class="checkbox-font">Oświadczam, że zapoznałem się {% if configuration.rule_file %}<a href="{{ configuration.rule_file.url }}" target="_blank">regulaminem</a>{% else %}regulaminem{% endif %} konkursu Saint-Gobain Trophy 2018. Wyrażam zgodę na administrowanie i przetwarzanie moich danych osobowych, które udostępniłem w Formularzu zgłoszeniowym, a także otrzymywanie informacji drogą elektroniczną, na warunkach określonych w ustawie z dnia 29 sierpnia 1997 r. o ochronie danych osobowych (Dz. U. z 2002 r. Nr101, poz. 926 ze zmianami) dla celów przeprowadzenia Konkursu Trophy 2018. Administratorem zbieranych danych osobowych jest Saint-Gobain Construction Products Polska Sp. z o.o. z siedzibą w Gliwicach, ul. Okrężna 16, 44-100 Gliwice.</span>
                    </label>
                    {{ form.checkbox_1.errors }}
                </div>

                <div class="checkbox small checkbox-text">
                    {% render_field form.checkbox_2 class="sc-checkbox" %}
                    <label for="{{ form.checkbox_2.auto_id }}" class="material-checkbox">

                        <span class="checkbox-font">Wyrażam zgodę na administrowanie i przetwarzanie moich danych osobowych, które udostępniłem w formularzu zgłoszeniowym, a także otrzymywanie informacji drogą elektroniczną dla potrzeb marketingowych firmy Saint-Gobain Construction Products Polska Sp. z o.o., ul. Okrężna 16, 44-100 Gliwice.</span>
                    </label>
                    {{ form.checkbox_2.errors }}
                </div>



                {% csrf_token %}
                <div class="text-right">
                    <button class="btn btn-primary button-wyslij">Wyślij zgłoszenie</button>
                </div>
                <br/>
            </form>

        </div>
        <div class="col-12 col-sm-2 col-md-2 hidden-xs hidden-sm"></div>
    </div>
</div>
    </div>

apps/website/templates/website/site/_top.html
{% load static %}{% load widget_tweaks %}


<div class="header-wrapper">

    <div class="baner text-center">

        <div class="skos_1">
            <img class="img-responsive" src="{% static 'website/images/skos.svg' %}" alt="">
        </div>

        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-3 saint-gobain">
                    <img class="img-responsive " src="{% static 'website/images/saint-gobain.png' %}" alt="">
                </div>
                <div class="col-sm-1 col-sm-offset-11">
                    <div class="green-label">
                        <div class="icons-top"><a href="https://www.linkedin.com/company/rigips-polska" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></div>
                        <div class="icons-top"><a href="https://www.facebook.com/pages/Rigips-Polska/495915043852036" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></div>
                        <div class="icons-top"><a href="https://www.youtube.com/channel/UCCDL4TDLDJbWNWuLTQX7xaw" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></div>
                    </div>
                </div>
                <!--<div class="pull-right">-->
                    <!--<a href="..." target="_blank" class=""><i class="fa fa-facebook" aria-hidden="true"></i></a>-->
                <!--</div> -->
            </div>
        <div class="trophy-wrapper">
            <span class="mini-title col-xs-12">Lokalna edycja XI międzynarodowego konkursu</span>
            <span class="trophy col-xs-12 trophy-line">Trophy</span>
            <span class="trophy col-xs-12">2018</span>
        </div>
            </div>

        <div class="skos_2">
            <img class="img-responsive" src="{% static 'website/images/skos_2.svg' %}" alt="">
        </div>

<div class="container text-center line-1"><span class="line"></span></div>
    </div>

      <div class="skos_3">
          <div class="opis-bg-mobile hidden-lg">
              <div class="opis-wrapper opis-bg-mobile ">
                  <div class="container">
                      <div class="row">
                          <div class=" col-md-3"></div>
                          <div class="col-xs-12 col-sm-12 col-md-6 welcome center-justified">
                              <h2>Zapraszamy do wzięcia udziału w konkursie</h2>
                              <p>Niniejszym ogłaszamy lokalną edycję XI międzynarodowego konkursu TROPHY. Konkurs ma na celu wyłonienie najlepszych polskich firm wykonawczych korzystających z systemów i produktów marki RIGIPS, które będą reprezentowały Polskę na międzynarodowym konkursie w Lizbonie w 2018 roku. Do konkursu mogą być zgłaszane obiekty zakończone i oddane do użytku do grudnia 2017. </p>
                              <img class="pull-right" src="{% static 'website/images/rigips_1.png' %}" alt="">
                          </div>
                          <div class=" col-md-3"></div>
                      </div>
                  </div>
              </div>
          </div>
            <div class="visible-lg">
              <div class="opis-wrapper ">
                  <div class="container">
                      <div class="row">
                          <div class=" col-md-3"></div>
                          <div class="col-xs-12 col-sm-12 col-md-6 welcome center-justified">
                              <h2>Zapraszamy do wzięcia udziału w konkursie</h2>
                              <p>Niniejszym ogłaszamy lokalną edycję XI międzynarodowego konkursu TROPHY. Konkurs ma na celu wyłonienie najlepszych polskich firm wykonawczych korzystających z systemów i produktów marki RIGIPS, które będą reprezentowały Polskę na międzynarodowym konkursie w Lizbonie w 2018 roku. Do konkursu mogą być zgłaszane obiekty zakończone i oddane do użytku do grudnia 2017. </p>
                              <img class="pull-right" src="{% static 'website/images/rigips_1.png' %}" alt="">
                          </div>
                          <div class=" col-md-3"></div>
                      </div>
                  </div>
              </div>
          </div>
      </div>

</div>

apps/website/templates/website/site/detail.html
Detail: {{ object }}

apps/website/templates/website/site/homepage.html
{% extends 'website/site/layout.html' %}
{% block body_content %}


    {% include "website/site/_top.html" %}
    {% include "website/site/_conditions.html" %}
    {% include "website/site/_form.html" %}

    {% include "website/site/_footer.html" %}

{% endblock %}

apps/website/templates/website/site/layout.html
<!DOCTYPE html>{% load static %}{% load compress %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Trophy 2018 - Lokalna edycja XI międzynarodowego konkursu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="SilverCube">
    <link href="{% static 'website/images/favicon.ico' %}" rel="shortcut icon" />
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!--GOOGLE FONT - Roboto-->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700&amp;subset=latin-ext" rel="stylesheet">
    {% compress css %}
    <link rel="stylesheet" href="{% static 'website/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/style/main.css' %}">
    <link href="{% static 'website/style/font-awesome.min.css' %}" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'website/style/style.css' %}">
    {% endcompress %}
    <script src="{% static 'website/scripts/jquery.min.js' %}"></script>
</head>
<body>
    {% block body_content %}

    {% endblock %}
    {% compress js %}
    <script src="{% static 'website/scripts/main.js' %}"></script>
    {% endcompress %}
</body>
</html>